/* Run: PLAYWRIGHT_MODULE=/path/to/playwright CHROMIUM_PATH=/path/to/chrome node tests/browser.cjs
   Or install Playwright and its Chromium, then: node tests/browser.cjs
   A local STUN responder supplies loopback candidates in isolated test environments. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const {spawn}=require('node:child_process');const dgram=require('node:dgram');
let server,browser,folder;const base='http://localhost:18787';const checks=[];const done=s=>{checks.push(s);console.log('PASS',s);};
const stun=dgram.createSocket('udp4');stun.on('message',(msg,remote)=>{if(msg.length<20||msg.readUInt16BE(0)!==1)return;const out=Buffer.alloc(32);out.writeUInt16BE(0x0101,0);out.writeUInt16BE(12,2);out.writeUInt32BE(0x2112a442,4);msg.copy(out,8,8,20);out.writeUInt16BE(0x0020,20);out.writeUInt16BE(8,22);out[25]=1;out.writeUInt16BE(remote.port^0x2112,26);const ip=remote.address.split('.').map(Number),cookie=[0x21,0x12,0xa4,0x42];for(let i=0;i<4;i++)out[28+i]=ip[i]^cookie[i];stun.send(out,remote.port,remote.address);});
async function disconnect(page){await page.click('#connection-status');await page.click('#disconnect');await page.waitForFunction(()=>!document.querySelector('#dialog').open&&document.querySelector('#connection-status').textContent.includes('Local only'));}
async function connect(page){await page.click('#connection-status');await page.click('#connection-form .primary');await page.waitForFunction(()=>document.querySelector('#live-connections').textContent.includes('Server connected'));await page.click('#close-dialog');}
async function screenshot(page,name){await page.screenshot({path:`tests/out/${name}.png`,fullPage:true,animations:'disabled'});}
(async()=>{
 await fs.mkdir('tests/out',{recursive:true});folder=await fs.mkdtemp(path.join(os.tmpdir(),'peerbench-browser-'));await new Promise(r=>stun.bind(19303,'127.0.0.1',r));
 server=spawn(process.execPath,['server/peerbench.mjs'],{env:{...process.env,PORT:'18787',DATA_DIR:folder}});await new Promise((r,j)=>{server.stdout.once('data',r);server.once('error',j);});
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--allow-loopback-in-peer-connection','--disable-features=WebRtcHideLocalIpsWithMdns','--use-gl=angle','--use-angle=swiftshader']});
 const contexts=[];for(let i=0;i<3;i++){const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await context.route('**/config.json',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({iceServers:[{urls:'stun:127.0.0.1:19303'}],persistByDefault:true})}));contexts.push(context);}
 const [a,b,c]=await Promise.all(contexts.map(x=>x.newPage()));const errors=[];for(const p of [a,b,c]){p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());}
 await a.goto(base);await a.waitForSelector('#create-first');await screenshot(a,'welcome');await a.click('#try-sample');await a.fill('#new-room-name','Community build');await a.click('#create-room-form .primary');await a.waitForSelector('.task-card');assert.equal(await a.locator('.task-card').count(),3);done('Create sample room and render three board stages');
 await a.click('#invite');await a.click('#connection-form .primary');await a.waitForFunction(()=>document.querySelector('#connection-status').textContent.includes('Server connected'));const invite=await a.inputValue('#invite-url');await a.click('#close-dialog');
 await b.goto(invite);await b.fill('#join-name','Jo');await b.click('#join-form .primary');await b.waitForSelector('.task-card');await a.waitForFunction(()=>document.querySelector('#connection-status').textContent.includes('peer'),null,{timeout:20000});done('Private invitation establishes a real WebRTC data channel');
 await a.click('[data-view="notes"]');await b.click('[data-view="notes"]');await a.fill('#note-body','A shared notebook.');await b.waitForFunction(()=>document.querySelector('#note-body').value==='A shared notebook.');await Promise.all([a.locator('#note-body').press('Home').then(()=>a.locator('#note-body').pressSequentially('Mike: ')),b.locator('#note-body').press('End').then(()=>b.locator('#note-body').pressSequentially(' And Jo.'))]);await a.waitForTimeout(500);assert.equal(await a.inputValue('#note-body'),await b.inputValue('#note-body'));assert.match(await a.inputValue('#note-body'),/Mike:.*And Jo/);done('Concurrent notebook edits converge without losing either contribution');
 await disconnect(a);await disconnect(b);await a.fill('#note-body',(await a.inputValue('#note-body'))+' Offline Mike.');await b.fill('#note-body',(await b.inputValue('#note-body'))+' Offline Jo.');await connect(a);await connect(b);await a.waitForFunction(()=>document.querySelector('#note-body').value.includes('Offline Jo.'));await b.waitForFunction(()=>document.querySelector('#note-body').value.includes('Offline Mike.'));assert.equal(await a.inputValue('#note-body'),await b.inputValue('#note-body'));done('Independent offline edits merge after reconnection');
 await a.fill('#chat-input','Let’s bring this to life.');await a.click('#chat-form button');await b.waitForSelector('text=Let’s bring this to life.');await a.click('[data-view="board"]');await a.click('#add-task');await a.fill('#task-title','Build the shared test rig');await a.selectOption('#task-status','doing');await a.fill('#task-assignee','Mike');await a.fill('#task-tags','prototype, electronics');await a.click('#task-form .primary');await b.click('[data-view="board"]');await b.waitForSelector('text=Build the shared test rig');done('Chat and task changes arrive on another device');
 await a.fill('#task-search','shared test rig');assert.equal(await a.locator('.task-card').count(),1);await a.fill('#task-search','');await a.getByRole('button',{name:'Edit task: Build the shared test rig'}).click();await a.click('#duplicate-task');await a.waitForFunction(()=>document.querySelectorAll('.task-card').length===5);await a.getByRole('button',{name:'Edit task: Build the shared test rig (copy)',exact:true}).click();await a.click('#delete-task');await a.click('#history');await a.click('[data-restore-item]');await a.click('#close-dialog');await a.waitForFunction(()=>document.querySelectorAll('.task-card').length===5);done('Search, duplicate, trash, and restore complete their full flows');
 await a.click('[data-view="files"]');const content=Buffer.from('Shared attachment.\n'.repeat(20000));await a.setInputFiles('#file-input',{name:'build-notes.txt',mimeType:'text/plain',buffer:content});await b.click('[data-view="files"]');await b.waitForSelector('text=build-notes.txt');await b.click('[data-file-action]');await b.waitForFunction(()=>document.querySelector('[data-file-action]')?.textContent.includes('Download'),null,{timeout:20000});const fileDownload=b.waitForEvent('download');await b.click('[data-file-action]');const file=await fileDownload;assert.deepEqual(await fs.readFile(await file.path()),content);done('Chunked peer attachment transfer, integrity verification, and download');
 const backupWait=a.waitForEvent('download');await a.click('#backup');const backup=await backupWait;await backup.saveAs('tests/out/backup.json');const exported=JSON.parse(await fs.readFile('tests/out/backup.json'));assert.equal(exported.assets.length,1);assert.equal(exported.key,undefined);done('Complete JSON backup includes local file bytes and excludes invitation key');
 await a.click('#history');await a.click('#make-snapshot');await a.waitForSelector('[data-restore-snapshot]');assert.equal(await a.locator('[data-restore-snapshot]').count(),1);await a.click('#close-dialog');
 await a.click('[data-view="board"]');await screenshot(a,'desktop');await a.click('#profile');await a.selectOption('#prefs-theme','dark');await a.click('#prefs-form .primary');await screenshot(a,'dark');assert.equal(await a.locator('html').getAttribute('data-theme'),'dark');await a.click('#profile');await a.selectOption('#prefs-theme','contrast');await a.click('#prefs-form .primary');await screenshot(a,'contrast');await a.click('#profile');await a.selectOption('#prefs-theme','light');await a.click('#prefs-form .primary');done('Light, dark, and high-contrast themes');
 await a.setViewportSize({width:390,height:844});await screenshot(a,'mobile');assert.equal(await a.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await a.click('#toggle-nav');await a.click('#close-nav');assert.equal(await a.locator('body').evaluate(el=>el.classList.contains('nav-collapsed')),true);done('390-pixel mobile layout and navigation without horizontal overflow');await a.setViewportSize({width:1440,height:1000});
 await a.click('#room-menu');await a.click('#menu-print');await a.emulateMedia({media:'print'});await a.pdf({path:'tests/out/report.pdf',format:'A4',printBackground:true});assert.match(await a.locator('#print-report').textContent(),/Build the shared test rig/);await a.emulateMedia({media:'screen'});done('Document-style printable report and PDF rendering');
 await a.click('#connection-status');await a.click('#disconnect');await b.click('#connection-status');await b.click('#disconnect');await c.goto(invite);await c.fill('#join-name','Late arrival');await c.click('#join-form .primary');await c.waitForSelector('.task-card');assert.equal(await c.locator('.task-card').count(),5);await c.click('[data-view="notes"]');await c.waitForFunction(()=>document.querySelector('#note-body').value.includes('Offline Mike.')&&document.querySelector('#note-body').value.includes('Offline Jo.'));done('Third device restores encrypted room archive while original peers are disconnected');
 await a.setInputFiles('#import-input','tests/out/backup.json');await a.waitForFunction(()=>document.querySelector('#room-title').textContent.endsWith('(restored)'));await a.click('[data-view="notes"]');assert.match(await a.inputValue('#note-body'),/Offline Jo/);await a.click('[data-view="files"]');await a.waitForSelector('[data-file-action]');assert.match(await a.locator('[data-file-action]').textContent(),/Download/);done('JSON backup restores into an independent room, including file bytes');
 await a.reload();await a.waitForSelector('#room-title');await a.click('[data-view="notes"]');assert.match(await a.inputValue('#note-body'),/Offline Mike/);await a.waitForFunction(()=>!!navigator.serviceWorker.controller);await contexts[0].setOffline(true);await a.reload();await a.waitForSelector('#room-title');await a.click('[data-view="notes"]');await a.fill('#note-body',(await a.inputValue('#note-body'))+' Works fully offline.');await a.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Saved on'));await a.reload();await a.waitForSelector('#room-title');await a.click('[data-view="notes"]');assert.match(await a.inputValue('#note-body'),/Works fully offline/);await contexts[0].setOffline(false);done('Offline app reload and edits persist through another offline reload');
 await a.click('#room-menu');await a.click('#menu-new');await a.fill('#new-room-name','Blank build');await a.click('#create-room-form .primary');await a.waitForFunction(()=>document.querySelector('#room-title').textContent==='Blank build');assert.equal(await a.locator('.task-card').count(),0);await a.click('[data-view="notes"]');await a.click('#add-note-empty');await a.fill('#note-title','A fresh page');await a.fill('#note-body','First idea');await a.locator('#note-body').press('Control+z');assert.equal(await a.inputValue('#note-body'),'');await a.locator('#note-body').press('Control+Shift+z');assert.equal(await a.inputValue('#note-body'),'First idea');await a.click('#delete-note');await a.click('#history');await a.click('[data-restore-item]');await a.click('#close-dialog');await a.waitForSelector('#note-body');assert.equal(await a.inputValue('#note-body'),'First idea');done('Fresh start, note creation, text undo/redo, deletion, and recovery');
 assert.deepEqual(errors,[]);done('No uncaught browser JavaScript errors');await fs.writeFile('tests/out/results.json',JSON.stringify({date:new Date().toISOString(),checks,errors},null,2));
 await browser.close();browser=null;server.kill();stun.close();await fs.rm(folder,{recursive:true,force:true});console.log(`${checks.length} browser workflow checks passed.`);
})().catch(async e=>{console.error(e);try{if(browser){for(const context of browser.contexts())for(const page of context.pages())await page.screenshot({path:'tests/out/failure-'+Date.now()+'.png',fullPage:true}).catch(()=>{});await browser.close();}}catch{}server?.kill();stun.close();process.exitCode=1;});
