import {uid,editText} from './model.js';
// Immutable revisions form a per-field DAG. Concurrent heads remain reviewable.
export function revisions(doc,kind,target,field){return [...doc.getMap('revisions')].map(([id,r])=>({id,...r})).filter(r=>(!kind||r.kind===kind)&&(!target||r.target===target)&&(!field||r.field===field)).sort((a,b)=>b.time-a.time||a.id.localeCompare(b.id));}
export function heads(doc,kind,target,field){const rows=revisions(doc,kind,target,field),parents=new Set(rows.flatMap(r=>r.parents||[]));return rows.filter(r=>!parents.has(r.id));}
export function record(doc,kind,target,field,before,after,actor,label='Edit',parents){const id=uid();doc.getMap('revisions').set(id,{kind,target,field,before:before??'',after:after??'',actor:String(actor||'Maker').slice(0,60),label,time:Date.now(),parents:parents||heads(doc,kind,target,field).map(r=>r.id)});return id;}
export function changeFields(doc,kind,id,fields,actor,label='Edit',basis){const item=doc.getMap(kind).get(id);if(!item)return;doc.transact(()=>{for(const [field,value]of Object.entries(fields)){const before=item.get(field);if(before===value&&!basis&&heads(doc,kind,id,field).length<2)continue;record(doc,kind,id,field,before,value,actor,label,basis?.[field]);item.set(field,value);}},'ui');}
export function conflicts(doc){const groups=new Map();for(const r of revisions(doc)){if(r.kind!=='tasks')continue;groups.set(r.target+':'+r.field,r);}return [...groups.values()].map(r=>({...r,choices:heads(doc,r.kind,r.target,r.field)})).filter(r=>new Set(r.choices.map(x=>JSON.stringify(x.after))).size>1);}
export function saveNoteRevision(doc,id,actor,label='Saved revision'){const n=doc.getMap('notes').get(id);if(!n)return;const rid=record(doc,'notes',id,'body','',n.get('body').toString(),actor,label);const map=doc.getMap('revisions');map.set(rid,{...map.get(rid),delta:n.get('body').toDelta()});return rid;}
export function restoreRevision(doc,r,actor){if(r.kind==='notes'&&r.field==='body'){const n=doc.getMap('notes').get(r.target);if(!n)throw Error('This note no longer exists.');saveNoteRevision(doc,r.target,actor,'Before restore');if(r.delta){const t=n.get('body');doc.transact(()=>{t.delete(0,t.length);t.applyDelta(r.delta);},'ui');}else editText(n.get('body'),r.after);saveNoteRevision(doc,r.target,actor,'Restored revision');}else changeFields(doc,r.kind,r.target,{[r.field]:r.after},actor,'Restored field');}
