import {Y,b64,unb64,uid,VERSION} from './model.js';
let db;
export async function database(){if(db)return db;db=await new Promise((resolve,reject)=>{const req=indexedDB.open('peerbench-v1',1);req.onupgradeneeded=()=>{const d=req.result;d.createObjectStore('rooms',{keyPath:'id'});const u=d.createObjectStore('updates',{autoIncrement:true});u.createIndex('room','room');d.createObjectStore('assets');d.createObjectStore('snapshots',{keyPath:'id'});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});return db;}
async function run(store,mode,fn){const d=await database();return new Promise((resolve,reject)=>{const tx=d.transaction(store,mode);let value;try{const r=fn(tx.objectStore(store));if(r)r.onsuccess=()=>{value=r.result;};}catch(e){reject(e);return;}tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error||Error('Storage failed'));tx.onabort=()=>reject(tx.error||Error('Storage aborted'));});}
export const listRooms=()=>run('rooms','readonly',s=>s.getAll());
export const putRoom=r=>run('rooms','readwrite',s=>s.put(r));
export const putAsset=(room,id,data)=>run('assets','readwrite',s=>s.put(data,room+':'+id));
export const getAsset=(room,id)=>run('assets','readonly',s=>s.get(room+':'+id));
export const removeAsset=(room,id)=>run('assets','readwrite',s=>s.delete(room+':'+id));
export async function loadDoc(room){const rows=await run('updates','readonly',s=>s.index('room').getAll(room));const doc=new Y.Doc();for(const row of rows)Y.applyUpdate(doc,new Uint8Array(row.data),'load');return doc;}
export function persistence(room,doc,onStatus){let queue=[],saving=false,failed=false,timer;const flush=async()=>{clearTimeout(timer);if(saving)return;if(!queue.length)return;saving=true;onStatus('saving');const items=queue;queue=[];try{const merged=Y.mergeUpdates(items);await run('updates','readwrite',s=>s.add({room,data:merged,time:Date.now()}));failed=false;onStatus(queue.length?'saving':'saved');}catch(e){queue.unshift(...items);failed=true;onStatus('error',e);}finally{saving=false;if(queue.length&&!failed)timer=setTimeout(flush,50);}};
 const listener=u=>{queue.push(u.slice());onStatus('saving');clearTimeout(timer);timer=setTimeout(flush,100);};doc.on('update',listener);return {flush,async settled(){await flush();while(saving)await new Promise(r=>setTimeout(r,20));if(queue.length){await flush();if(failed)throw Error('Local saving failed. Export a backup now.');}},get pending(){return saving||queue.length>0;},destroy(){clearTimeout(timer);doc.off('update',listener);}};}
export async function storeFull(room,doc){await run('updates','readwrite',s=>s.add({room,data:Y.encodeStateAsUpdate(doc),time:Date.now()}));}
export async function backup(room,doc,withAssets=true){const assets=[];if(withAssets)for(const [id]of doc.getMap('files')){const data=await getAsset(room.id,id);if(data)assets.push({id,data:b64(new Uint8Array(await data.arrayBuffer())),type:data.type});}return {format:'peerbench',schema:1,version:VERSION,exported:new Date().toISOString(),name:doc.getMap('meta').get('name')||room.name,update:b64(Y.encodeStateAsUpdate(doc)),assets};}
export async function makeSnapshot(room,doc,name){const item={id:uid(),room:room.id,name:name||new Date().toLocaleString(),created:Date.now(),update:b64(Y.encodeStateAsUpdate(doc))};await run('snapshots','readwrite',s=>s.put(item));return item;}
export const snapshots=async room=>(await run('snapshots','readonly',s=>s.getAll())).filter(x=>x.room===room).sort((a,b)=>b.created-a.created);
export const deleteSnapshot=id=>run('snapshots','readwrite',s=>s.delete(id));
export async function removeRoom(room){const d=await database();await new Promise((resolve,reject)=>{const tx=d.transaction(['rooms','updates','assets','snapshots'],'readwrite');tx.objectStore('rooms').delete(room);const rq=tx.objectStore('updates').index('room').openCursor(room);rq.onsuccess=()=>{const c=rq.result;if(c){c.delete();c.continue();}};for(const store of ['assets','snapshots']){const q=tx.objectStore(store).openCursor();q.onsuccess=()=>{const c=q.result;if(c){if(store==='assets'?String(c.key).startsWith(room+':'):c.value.room===room)c.delete();c.continue();}};}tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
