import {uid,b64,unb64,sha} from './model.js';
import * as S from './storage.js';
export const FILE_LIMIT=50*1024*1024,ROOM_FILES_LIMIT=250*1024*1024,CHUNK=32768;
const pause=()=>new Promise(r=>setTimeout(r,20));
export class Transfers{
 constructor(room,doc,{network,name,changed,toast}){this.room=room;this.doc=doc;this.network=network;this.name=name;this.changed=changed;this.toast=toast;this.states=new Map();this.queue=[];this.busy=false;this.destroyed=false;this.waiter=null;this.senders=new Set();this.cancelled=new Set();}
 async restore(){for(const id of this.doc.getMap('files').keys()){const state=await S.getAsset(this.room.id,'transfer-'+id);if(state){state.status=state.status==='complete'?'complete':'paused';this.states.set(id,state);}}this.changed();}
 async add(files){const ids=[];for(const file of files){if(file.size>FILE_LIMIT)throw Error(file.name+' exceeds the 50 MiB file limit.');const total=[...this.doc.getMap('files').values()].reduce((s,f)=>s+(f.size||0),0);if(total+file.size>ROOM_FILES_LIMIT)throw Error('Room attachments have reached 250 MiB, including trash. Start a new room for more.');const id=uid(),hash=await sha(await file.arrayBuffer());await S.putAsset(this.room.id,id,file);this.doc.getMap('files').set(id,{name:file.name.slice(0,250),size:file.size,type:file.type||'application/octet-stream',hash,by:this.name(),created:Date.now(),deleted:false});ids.push(id);}this.changed();return ids;}
 async update(id,fields){const s=Object.assign(this.states.get(id)||{offset:0},fields);this.states.set(id,s);await S.putAsset(this.room.id,'transfer-'+id,s);if(!this.destroyed)this.changed();return s;}
 async enqueue(id,direction='download',source='peers'){if(this.destroyed)return;if(this.states.get(id)?.status==='receiving'||this.states.get(id)?.status==='uploading'||this.states.get(id)?.status==='queued')return;let state=await S.getAsset(this.room.id,'transfer-'+id);const legacy=await S.getAsset(this.room.id,'partial-'+id);if(legacy instanceof Blob){for(let i=0;i<legacy.size;i+=CHUNK)await S.putTransferChunk(this.room.id,id,i,legacy.slice(i,i+CHUNK),{offset:Math.min(i+CHUNK,legacy.size),status:'paused',direction:'download',source});await S.removeAsset(this.room.id,'partial-'+id);state={offset:legacy.size};}this.states.delete(id);await this.update(id,{offset:state?.direction===direction||!state?.direction?state?.offset||0:0,direction,source,status:'queued',error:'',peer:null,token:uid()});this.queue.push(id);this.pump();}
 async pause(id){const s=this.states.get(id);if(!s)return;s.status='paused';if(this.waiter?.id===id)this.waiter.reject(Error('Paused'));await this.update(id,{status:'paused'});this.network()?.broadcast({kind:'file-cancel',id,transfer:s.token});}
 async cancel(id){await this.pause(id);this.queue=this.queue.filter(x=>x!==id);await S.clearTransfer(this.room.id,id);this.states.delete(id);this.changed();}
 async pump(){if(this.busy||this.destroyed)return;this.busy=true;try{while(this.queue.length&&!this.destroyed){const id=this.queue.shift(),s=this.states.get(id);if(!s||s.status!=='queued')continue;try{if(s.direction==='upload')await this.upload(id,s);else await this.download(id,s);}catch(e){if(!this.destroyed&&this.states.get(id)===s&&s.status!=='paused')await this.update(id,{status:'error',error:e.message});}}}finally{this.busy=false;}}
 alive(id,s){return !this.destroyed&&this.states.get(id)===s&&!['paused','error'].includes(s.status);}
 async download(id,initial){let s=await this.update(id,{status:'receiving'});const f=this.doc.getMap('files').get(id);if(!f||f.deleted||f.size>FILE_LIMIT)throw Error('File is missing, in trash, or exceeds 50 MiB.');let net=this.network();if(!net||(!net.ready&&![...net.peers.values()].some(p=>p.dc?.readyState==='open')))throw Error('Connect to a file holder or enabled attachment archive, then retry.');
 // Derive resume frontier from actual contiguous chunks, never trust a stored offset alone.
 const prior=await S.transferParts(this.room.id,id);let frontier=0;for(const p of prior){if(p.offset!==frontier)break;frontier+=p.blob.size;}s.offset=frontier;
 while(s.offset<f.size||f.size===0&&s.offset===0){if(!this.alive(id,s))return;const offset=s.offset;let bytes;
 if(s.source==='archive'){const result=await net.request('asset-get',{id,index:Math.floor(offset/CHUNK)});if(!result.box)throw Error('This file is incomplete or unavailable in the archive. Try a connected holder.');const packet=await net.crypto.open(result.box);if(packet.id!==id||packet.offset!==offset||typeof packet.data!=='string')throw Error('Archive file chunk does not match this transfer.');bytes=unb64(packet.data);}
 else{const packet=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{if(this.waiter?.id===id)this.waiter=null;reject(Error('No file data arrived. Reconnect a holder and retry.'));},15000);this.waiter={id,offset,token:s.token,source:s.peer,resolve:value=>{clearTimeout(timer);this.waiter=null;resolve(value);},reject:e=>{clearTimeout(timer);this.waiter=null;reject(e);}};const message={kind:'file-request',id,offset,window:1,transfer:s.token};(s.peer?net.reply(s.peer,message):net.broadcast(message)).catch(reject);});s.peer=packet.from;bytes=unb64(packet.data);}
 if(!this.alive(id,s))return;if(bytes.length>CHUNK||offset+bytes.length>f.size||(!bytes.length&&f.size>0))throw Error('Invalid file chunk size.');s.offset+=bytes.length;await S.putTransferChunk(this.room.id,id,offset,new Blob([bytes]),{...s});this.changed();if(s.offset===f.size)break;await pause();}
 if(!this.alive(id,s))return;const parts=await S.transferParts(this.room.id,id);const blob=new Blob(parts.map(p=>p.blob),{type:f.type});if(blob.size!==f.size||await sha(await blob.arrayBuffer())!==f.hash){await S.clearTransfer(this.room.id,id);s.offset=0;throw Error('Integrity check failed. Partial bytes were discarded; retry.');}if(!this.alive(id,s))return;await S.putAsset(this.room.id,id,blob);await S.clearTransfer(this.room.id,id);this.states.delete(id);this.changed();this.toast(f.name+' received and verified.');}
 async upload(id,initial){let s=await this.update(id,{status:'uploading'});const net=this.network(),f=this.doc.getMap('files').get(id),blob=await S.getAsset(this.room.id,id);if(!net?.ready)throw Error('Connect to an attachment-enabled server first.');if(!blob||!f||f.deleted)throw Error('Download the file to this device before archiving it.');const info=await net.request('asset-info',{id});if(!info.enabled)throw Error('Attachment hosting is disabled on this server.');s.offset=Math.min(info.next*CHUNK,blob.size);for(let i=info.next;i<Math.max(1,Math.ceil(blob.size/CHUNK));i++){if(!this.alive(id,s))return;const offset=i*CHUNK,data=b64(new Uint8Array(await blob.slice(offset,offset+CHUNK).arrayBuffer()));const box=await net.crypto.seal({id,offset,data});await net.request('asset-put',{id,index:i,box});if(!this.alive(id,s))return;s.offset=Math.min(offset+CHUNK,blob.size);await S.putAsset(this.room.id,'transfer-'+id,{...s});this.changed();await pause();}if(!this.alive(id,s))return;const current=this.doc.getMap('files').get(id);this.doc.getMap('files').set(id,{...current,hosted:true});await this.update(id,{status:'complete',offset:blob.size});this.toast(f.name+' encrypted and archived.');}
 async handle({from,message:m}){const net=this.network();if(!net||this.destroyed)return;
 if(m.kind==='file-cancel'){this.cancelled.add(from+':'+m.id);return;}
 if(m.kind==='file-request'){const f=this.doc.getMap('files').get(m.id);if(!f||f.deleted||!Number.isInteger(m.offset)||m.offset<0||m.offset>f.size)return;const key=from+':'+m.id;if(this.senders.has(key))return;this.senders.add(key);this.cancelled.delete(key);try{const blob=await S.getAsset(this.room.id,m.id);if(!blob){await net.reply(from,{kind:'file-missing',id:m.id});return;}for(let offset=m.offset;offset<Math.max(blob.size,1);offset+=CHUNK){if(this.destroyed||this.cancelled.has(key))break;const data=b64(new Uint8Array(await blob.slice(offset,offset+CHUNK).arrayBuffer()));await net.reply(from,{kind:'file-chunk',id:m.id,offset,data,last:offset+CHUNK>=blob.size,transfer:m.transfer});if(m.window===1)break;await pause();}}finally{this.senders.delete(key);}}
 if(m.kind==='file-chunk'){const w=this.waiter;if(!w||w.id!==m.id||w.offset!==m.offset||w.source&&w.source!==from||m.transfer&&m.transfer!==w.token||typeof m.data!=='string'||m.data.length>45000)return;w.resolve({from,data:m.data});}
 }
 async clearAll(){for(const id of [...this.states.keys()])await this.cancel(id);await S.clearPartials(this.room.id);}
 destroy(){this.destroyed=true;this.waiter?.reject(Error('Room closed'));this.waiter=null;this.queue=[];for(const [id,s]of this.states)if(['receiving','uploading','queued'].includes(s.status)){s.status='paused';S.putAsset(this.room.id,'transfer-'+id,{...s}).catch(()=>{});}}
}
