import {Y,uid,b64,unb64,roomCrypto} from './model.js';
const MAX_TEXT=8*1024*1024;
export class Collaboration extends EventTarget {
 constructor(room,doc,options={}){super();this.room=room;this.doc=doc;this.options=options;this.id=uid();this.peers=new Map();this.members=new Set();this.seen=new Set();this.ws=null;this.stopped=true;this.ready=false;this.lastAck=0;this.serverSaved=0;this.pendingStores=new Set();this.lastUpdateId=null;this.queue=Promise.resolve();this.receiving=Promise.resolve();this.state='offline';this.error='';this.listener=(u,origin)=>{if(origin==='remote'||origin==='load')return;this.lastAck=0;this.serverSaved=0;this.changed();if(!this.stopped)this.sendUpdate(u);};doc.on('update',this.listener);}
 changed(){this.dispatchEvent(new Event('status'));}
 async start(){this.stopped=false;this.crypto=await roomCrypto(this.room.id,this.room.key);this.connect();this.tick=setInterval(()=>{this.broadcast({kind:'presence',name:this.options.name||'Maker',view:this.options.view||'board',time:Date.now()});for(const [id,p]of this.peers){if(p.lastSeen&&Date.now()-p.lastSeen>45000){p.name='Connecting…';this.changed();}}},12000);}
 connect(){if(this.stopped)return;this.state='connecting';this.error='';this.changed();try{this.ws=new WebSocket(this.room.server);}catch(e){this.fail(e.message);return;}const ws=this.ws;ws.onopen=()=>{ws.send(JSON.stringify({t:'join',room:this.room.id,auth:this.crypto.auth,peer:this.id}));};ws.onmessage=e=>{this.receiving=this.receiving.then(()=>this.handleServer(JSON.parse(e.data))).catch(err=>{this.error='Could not read a peer message: '+err.message;this.changed();});};ws.onerror=()=>{this.error='Connection server unavailable. Your local work is preserved.';this.changed();};ws.onclose=()=>{if(this.ws!==ws)return;this.ready=false;this.pendingStores.clear();this.state='offline';this.changed();if(!this.stopped)this.retry=setTimeout(()=>this.connect(),3000);};}
 fail(message){this.error=message;this.changed();}
 async handleServer(m){
 if(m.t==='error'){this.fail(m.message);return;}
 if(m.t==='welcome'){this.state='connected';this.members=new Set(m.peers);for(const id of m.peers)await this.makePeer(id,true);this.changed();}
 if(m.t==='replay')await this.receiveBox(m.box,'archive');
 if(m.t==='ready'){this.ready=true;await this.sendUpdate(Y.encodeStateAsUpdate(this.doc));await this.broadcast({kind:'presence',name:this.options.name||'Maker',view:this.options.view||'board'});this.changed();}
 if(m.t==='peer'){this.members.add(m.peer);this.changed();}
 if(m.t==='left'){this.members.delete(m.peer);this.peers.get(m.peer)?.pc.close();this.peers.delete(m.peer);this.changed();}
 if(m.t==='signal'){const data=await this.crypto.open(m.box);let p=this.peers.get(m.from);if(!p)p=await this.makePeer(m.from,false);if(data.description){await p.pc.setRemoteDescription(data.description);for(const c of p.ice.splice(0))await p.pc.addIceCandidate(c);if(data.description.type==='offer'){await p.pc.setLocalDescription(await p.pc.createAnswer());await this.signal(m.from,{description:p.pc.localDescription.toJSON()});}}else if(data.candidate){if(p.pc.remoteDescription)await p.pc.addIceCandidate(data.candidate);else p.ice.push(data.candidate);}}
 if(m.t==='relay')await this.receiveBox(m.box,m.from);
 if(m.t==='stored'){this.pendingStores.delete(m.id);if(!this.pendingStores.size&&m.id===this.lastUpdateId)this.serverSaved=Date.now();this.changed();}
 }
 async signal(to,data){const box=await this.crypto.seal(data);this.socket({t:'signal',to,box});}
 socket(data){if(this.ws?.readyState===WebSocket.OPEN){this.ws.send(JSON.stringify(data));return true;}return false;}
 async makePeer(id,offer){if(this.peers.has(id))return this.peers.get(id);if(this.peers.size>=10)return {pc:{setRemoteDescription:async()=>{throw Error('Room has reached its 10-peer connection target.');}},ice:[]};
 const pc=new RTCPeerConnection({iceServers:this.options.iceServers||[]});const p={pc,dc:null,ice:[],name:'Collaborator',view:'',lastSeen:Date.now(),queue:Promise.resolve(),fragments:new Map(),route:'connecting'};this.peers.set(id,p);
 pc.onicecandidate=e=>{if(e.candidate)this.signal(id,{candidate:e.candidate.toJSON()}).catch(e=>this.fail(e.message));};
 pc.onconnectionstatechange=()=>{p.route=pc.connectionState;if(pc.connectionState==='failed')this.error='A direct connection failed; encrypted server relay is available while connected. Configure TURN for direct-channel fallback.';this.changed();};
 const attach=dc=>{p.dc=dc;dc.bufferedAmountLowThreshold=64000;dc.onopen=async()=>{p.route='direct';this.changed();try{await this.sendPeer(id,await this.crypto.seal({kind:'update',id:uid(),update:b64(Y.encodeStateAsUpdate(this.doc))}));await this.sendPeer(id,await this.crypto.seal({kind:'presence',name:this.options.name||'Maker',view:this.options.view||'board'}));const stats=await pc.getStats();for(const s of stats.values())if(s.type==='candidate-pair'&&s.state==='succeeded'){const candidate=stats.get(s.localCandidateId);if(candidate?.candidateType==='relay')p.route='TURN';}this.changed();}catch(e){this.fail(e.message);}};dc.onclose=()=>{p.route='closed';this.changed();};dc.onerror=()=>{p.route='error';this.changed();};dc.onmessage=e=>{this.receiving=this.receiving.then(async()=>{const chunk=JSON.parse(e.data);if(typeof chunk.mid!=='string'||!Number.isInteger(chunk.n)||chunk.n<1||chunk.n>750||!Number.isInteger(chunk.i)||chunk.i<0||chunk.i>=chunk.n||typeof chunk.s!=='string'||chunk.s.length>14000)return;for(const [key,f] of p.fragments)if(Date.now()-f.time>60000)p.fragments.delete(key);let f=p.fragments.get(chunk.mid);if(!f){if(p.fragments.size>=10)return;f={parts:new Array(chunk.n),got:0,time:Date.now()};p.fragments.set(chunk.mid,f);}if(f.parts.length!==chunk.n)return;if(f.parts[chunk.i]===undefined){f.parts[chunk.i]=chunk.s;f.got++;}if(f.got===chunk.n){p.fragments.delete(chunk.mid);await this.receiveBox(JSON.parse(f.parts.join('')),id);}}).catch(e=>this.fail('Peer transfer failed: '+e.message));};};
 pc.ondatachannel=e=>attach(e.channel);if(offer){attach(pc.createDataChannel('peerbench-v1'));await pc.setLocalDescription(await pc.createOffer());await this.signal(id,{description:pc.localDescription.toJSON()});}return p;
 }
 async sendPeer(id,box){const p=this.peers.get(id);if(!p?.dc||p.dc.readyState!=='open')return false;const text=JSON.stringify(box);if(text.length>MAX_TEXT)throw Error('Room update is too large to transfer. Export a backup and start an archive room.');const mid=uid(),n=Math.ceil(text.length/12000);p.queue=p.queue.catch(()=>{}).then(async()=>{for(let i=0;i<n;i++){const deadline=Date.now()+15000;while(p.dc.bufferedAmount>128000){if(p.dc.readyState!=='open'||Date.now()>deadline)throw Error('Peer transfer interrupted. Reconnect to retry.');await new Promise(r=>setTimeout(r,20));}if(p.dc.readyState!=='open')throw Error('Peer disconnected.');p.dc.send(JSON.stringify({mid,n,i,s:text.slice(i*12000,(i+1)*12000)}));}});await p.queue;return true;}
 broadcast(value,{persist=false}={}){const operation=this.queue.catch(()=>{}).then(async()=>{if(!this.crypto)return;const box=await this.crypto.seal(value);const direct=[];for(const [id,p]of this.peers){if(p.dc?.readyState==='open'){try{await this.sendPeer(id,box);direct.push(id);}catch{}}}if(this.ready){this.socket({t:'relay',box,exclude:direct});if(persist&&this.room.persist){this.pendingStores.add(value.id);this.serverSaved=0;this.socket({t:'store',box,id:value.id});this.changed();}}});this.queue=operation;operation.catch(e=>this.fail(e.message));return operation;}
 sendUpdate(update){const id=uid();this.lastUpdateId=id;return this.broadcast({kind:'update',id,update:b64(update)},{persist:true});}
 async receiveBox(box,from){const m=await this.crypto.open(box);if(m.kind==='update'){if(typeof m.update!=='string'||m.update.length>MAX_TEXT||typeof m.id!=='string')throw Error('Invalid room update.');if(!this.seen.has(m.id)){Y.applyUpdate(this.doc,unb64(m.update),'remote');this.seen.add(m.id);if(this.seen.size>2000)this.seen.delete(this.seen.values().next().value);}if(from!=='archive')await this.reply(from,{kind:'ack',id:m.id});}
 else if(m.kind==='ack'){if(m.id===this.lastUpdateId)this.lastAck=Date.now();this.changed();}
 else if(m.kind==='presence'){const p=this.peers.get(from);if(p){p.name=String(m.name||'Maker').slice(0,60);p.view=String(m.view||'').slice(0,20);p.lastSeen=Date.now();}this.changed();}
 else if(m.kind==='file-request'||m.kind==='file-chunk'||m.kind==='file-missing')this.dispatchEvent(new CustomEvent('file',{detail:{from,message:m}}));
 }
 async reply(to,value){const box=await this.crypto.seal(value);if(!await this.sendPeer(to,box))this.socket({t:'relay',to,box});}
 presence(name,view){this.options.name=name;this.options.view=view;return this.broadcast({kind:'presence',name,view});}
 stop(){this.stopped=true;clearTimeout(this.retry);clearInterval(this.tick);this.ws?.close();this.ws=null;this.ready=false;for(const p of this.peers.values())p.pc.close();this.peers.clear();this.members.clear();this.state='offline';this.changed();}
 destroy(){this.stop();this.doc.off('update',this.listener);}
}
