import {Y,uid,b64} from './model.js';
import {getAsset} from './storage.js';
import {escapeHTML as esc} from './notebook.js';
const number=(x,fallback=0)=>Number.isFinite(Number(x))?Math.max(-10000,Math.min(10000,Number(x))):fallback;
const color=x=>/^#[0-9a-f]{6}$/i.test(x)?x:'#f4d976';
const raster=t=>/^image\/(png|jpeg|webp|gif)$/.test(t||'');
export class Whiteboard{
 constructor(host,doc,room,{toast,download,files}){this.host=host;this.doc=doc;this.room=room;this.toast=toast;this.download=download;this.files=files;this.map=doc.getMap('drawing');this.selected=null;this.camera={x:0,y:0,w:1000,h:650};this.urls=new Map();this.loading=new Set();this.undo=new Y.UndoManager(this.map,{trackedOrigins:new Set(['whiteboard'])});this.observer=()=>{this.render();if(!this.inspector?.contains(document.activeElement))this.inspect();};this.map.observeDeep(this.observer);this.mount();}
 rows(){return [...this.map].filter(([,v])=>v instanceof Y.Map&&!v.get('deleted')).map(([id,v])=>({id,...v.toJSON()}));}
 mount(){this.host.innerHTML=`<div class="drawing-tools"><label>Tool <select id="draw-tool"><option value="select">Select / move</option><option value="pan">Pan</option><option value="sketch">Sketch</option></select></label><label>New object <select id="draw-kind"><option value="sticky">Sticky note</option><option value="rect">Rectangle</option><option value="ellipse">Ellipse</option><option value="connector">Connector</option><option value="image">Image from files</option></select></label><button id="draw-add" class="secondary">+ Add</button><button id="draw-undo" class="icon-button" aria-label="Undo whiteboard change">↶</button><button id="draw-redo" class="icon-button" aria-label="Redo whiteboard change">↷</button><button id="draw-out" class="icon-button" aria-label="Zoom out">−</button><button id="draw-in" class="icon-button" aria-label="Zoom in">+</button><button id="draw-fit" class="text-button">Fit all</button><label class="sr-only" for="draw-export-format">Export format</label><select id="draw-export-format"><option value="svg">SVG</option><option value="png">PNG</option></select><button id="draw-export" class="secondary">↓ Export</button></div><p class="muted drawing-help">Add an object, then select it to edit. Drag to move; arrow keys move selected objects. Sketch with a pointer, or connect shapes. Changes save with this room.</p><div class="drawing-layout"><svg id="drawing" role="application" aria-label="Shared whiteboard. Use the object list and inspector for keyboard editing." tabindex="0" xmlns="http://www.w3.org/2000/svg"></svg><aside class="drawing-inspector"><label class="field">Objects<select id="draw-objects" size="5" aria-label="Whiteboard objects"></select></label><div id="draw-inspector"></div></aside></div><p id="drawing-status" class="muted" role="status"></p>`;
 const q=s=>this.host.querySelector(s);this.svg=q('#drawing');this.inspector=q('#draw-inspector');q('#draw-add').onclick=()=>this.add(q('#draw-kind').value);q('#draw-undo').onclick=()=>this.undo.undo();q('#draw-redo').onclick=()=>this.undo.redo();q('#draw-in').onclick=()=>this.zoom(.8);q('#draw-out').onclick=()=>this.zoom(1.25);q('#draw-fit').onclick=()=>this.fit();q('#draw-export').onclick=()=>this.export(q('#draw-export-format').value).catch(e=>this.toast(e.message));q('#draw-objects').onchange=e=>{this.selected=e.target.value;this.render();this.inspect();};this.svg.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();this.zoom(e.deltaY>0?1.1:.9);}},{passive:false});
 this.svg.onpointerdown=e=>{const p=this.point(e),tool=q('#draw-tool').value,id=e.target.closest('[data-object]')?.dataset.object;if(tool==='sketch'){this.drag={kind:'sketch',points:[[p.x,p.y]]};}else if(tool==='pan'||!id){this.drag={kind:'pan',p,c:{...this.camera}};}else{this.selected=id;const item=this.map.get(id);this.drag=item.get('kind')==='connector'?null:{kind:'move',id,p,x:item.get('x')||0,y:item.get('y')||0};this.inspect();}this.svg.setPointerCapture(e.pointerId);this.svg.focus();this.render();};
 this.svg.onpointermove=e=>{if(!this.drag)return;const p=this.point(e),d=this.drag;if(d.kind==='pan'){this.camera.x=d.c.x+(d.p.x-p.x);this.camera.y=d.c.y+(d.p.y-p.y);d.c={...this.camera};}if(d.kind==='move'){this.preview={id:d.id,x:d.x+p.x-d.p.x,y:d.y+p.y-d.p.y};}if(d.kind==='sketch'&&d.points.length<1500)d.points.push([p.x,p.y]);this.render();};
 this.svg.onpointerup=()=>{const d=this.drag;if(!d)return;if(d.kind==='move'&&this.preview)this.change(d.id,{x:this.preview.x,y:this.preview.y});if(d.kind==='sketch'&&d.points.length>1)this.create({kind:'sketch',x:0,y:0,w:1,h:1,points:d.points,color:'#355ccc',text:'Sketch'});this.drag=null;this.preview=null;this.render();this.inspect();};this.svg.onpointercancel=()=>{this.drag=null;this.preview=null;this.render();};
 this.svg.onkeydown=e=>{const m=this.map.get(this.selected);if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();e.shiftKey?this.undo.redo():this.undo.undo();return;}if(!m)return;const moves={ArrowLeft:[-10,0],ArrowRight:[10,0],ArrowUp:[0,-10],ArrowDown:[0,10]};if(moves[e.key]){e.preventDefault();const [x,y]=moves[e.key];this.change(this.selected,{x:(m.get('x')||0)+x,y:(m.get('y')||0)+y});this.inspect();}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();this.change(this.selected,{deleted:true});this.selected=null;this.inspect();}};this.render();this.inspect();
 }
 point(e){const r=this.svg.getBoundingClientRect();return{x:this.camera.x+(e.clientX-r.left)/r.width*this.camera.w,y:this.camera.y+(e.clientY-r.top)/r.height*this.camera.h};}
 create(fields){if(this.rows().length>=500){this.toast('This whiteboard supports 500 objects. Start a new room for a larger drawing.');return;}const id=uid(),m=new Y.Map();this.undo.stopCapturing();this.doc.transact(()=>{this.map.set(id,m);for(const [k,v]of Object.entries({kind:'rect',x:100,y:100,w:180,h:100,text:'',color:'#f4d976',deleted:false,...fields}))m.set(k,v);},'whiteboard');this.selected=id;this.render();this.inspect();return id;}
 add(kind){const rows=this.rows();if(kind==='connector'&&rows.filter(r=>r.kind!=='connector').length<2){this.toast('Add two shapes first, then connect them.');return;}if(kind==='image'){const images=[...this.doc.getMap('files')].filter(([,f])=>!f.deleted&&raster(f.type));if(!images.length){this.toast('Add a PNG, JPEG, WebP, or GIF in Files, then insert it here.');this.files();return;}this.create({kind,asset:images[0][0],x:this.camera.x+this.camera.w/2-100,y:this.camera.y+this.camera.h/2-70,w:200,h:140,text:images[0][1].name});return;}const shapes=rows.filter(r=>r.kind!=='connector');this.create({kind,x:this.camera.x+this.camera.w/2-90,y:this.camera.y+this.camera.h/2-60,text:kind==='sticky'?'A good idea':kind==='connector'?'Connect':'',...(kind==='connector'?{from:shapes[0].id,to:shapes[1].id}:{})});}
 change(id,fields){const m=this.map.get(id);if(!m)return;this.undo.stopCapturing();this.doc.transact(()=>{for(const [k,v]of Object.entries(fields))m.set(k,typeof v==='number'?number(v):v);},'whiteboard');}
 zoom(scale){const c=this.camera,w=Math.max(250,Math.min(6000,c.w*scale)),h=w*.65;this.camera={x:c.x+(c.w-w)/2,y:c.y+(c.h-h)/2,w,h};this.render();}
 bounds(){const rows=this.rows().filter(r=>r.kind!=='connector');if(!rows.length)return{x:0,y:0,w:1000,h:650};const points=rows.flatMap(r=>r.kind==='sketch'?(r.points||[]).map(p=>[number(p[0])+number(r.x),number(p[1])+number(r.y)]):[[number(r.x),number(r.y)],[number(r.x)+number(r.w,180),number(r.y)+number(r.h,100)]]);const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);return{x:Math.min(...xs)-40,y:Math.min(...ys)-40,w:Math.max(300,Math.max(...xs)-Math.min(...xs)+80),h:Math.max(195,Math.max(...ys)-Math.min(...ys)+80)};}
 fit(){const b=this.bounds();if(b.w/b.h>1000/650)b.h=b.w*.65;else b.w=b.h/0.65;this.camera=b;this.render();}
 objectSVG(item,rows,urls=this.urls,select=true){const o=this.preview?.id===item.id?{...item,...this.preview}:item,x=number(o.x),y=number(o.y),w=Math.max(10,number(o.w,180)),h=Math.max(10,number(o.h,100)),fill=color(o.color),selected=select&&o.id===this.selected,stroke=selected?'#355ccc':'#24323d';let inner='';
 if(o.kind==='connector'){const a=rows.find(r=>r.id===o.from),b=rows.find(r=>r.id===o.to);if(!a||!b)return '';const edge=(o,t)=>{const w=Math.max(10,number(o.w,180)),h=Math.max(10,number(o.h,100)),cx=number(o.x)+w/2,cy=number(o.y)+h/2,dx=number(t.x)+number(t.w,180)/2-cx,dy=number(t.y)+number(t.h,100)/2-cy;const r=o.kind==='ellipse'?1/Math.sqrt((dx/(w/2))**2+(dy/(h/2))**2):Math.min(w/2/Math.abs(dx||.001),h/2/Math.abs(dy||.001));return[cx+dx*(Number.isFinite(r)?r:0),cy+dy*(Number.isFinite(r)?r:0)];};const start=edge(a,b),end=edge(b,a);inner=`<path d="M${start.join(' ')} L${end.join(' ')}" fill="none" stroke="${stroke}" stroke-width="${selected?5:3}" marker-end="url(#arrow)"/>`;}
 else if(o.kind==='sketch'){const pts=Array.isArray(o.points)?o.points.slice(0,1500).map(p=>`${number(p?.[0])+x},${number(p?.[1])+y}`).join(' '):'';inner=`<polyline points="${pts}" fill="none" stroke="${fill}" stroke-width="${selected?5:3}" stroke-linejoin="round" stroke-linecap="round"/>`;}
 else{if(o.kind==='ellipse')inner=`<ellipse cx="${x+w/2}" cy="${y+h/2}" rx="${w/2}" ry="${h/2}" fill="${fill}" stroke="${stroke}" stroke-width="${selected?4:2}"/>`;else inner=`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${o.kind==='sticky'?2:10}" fill="${o.kind==='image'?'#f2f0e9':fill}" stroke="${stroke}" stroke-width="${selected?4:2}"/>`;
 if(o.kind==='image'&&urls.get(o.asset))inner+=`<image x="${x+2}" y="${y+2}" width="${w-4}" height="${h-4}" href="${esc(urls.get(o.asset))}" preserveAspectRatio="xMidYMid meet"/>`;else{const lines=String(o.text|| (o.kind==='image'?'Get image in Files':'')).match(/.{1,24}/g)||[];inner+=`<text x="${x+14}" y="${y+28}" font-family="system-ui,sans-serif" font-size="16" fill="#202c39">${lines.slice(0,Math.max(1,Math.floor((h-20)/22))).map((l,i)=>`<tspan x="${x+14}" dy="${i?22:0}">${esc(l)}</tspan>`).join('')}</text>`;}}
 return `<g data-object="${esc(o.id)}" aria-label="${esc(o.text||o.kind)}">${inner}</g>`;
 }
 content(urls,select=true){const rows=this.rows();return `<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="#24323d"/></marker></defs>`+[...rows.filter(r=>r.kind==='connector'),...rows.filter(r=>r.kind!=='connector')].map(r=>this.objectSVG(r,rows,urls,select)).join('');}
 render(){if(!this.svg)return;const c=this.camera;this.svg.setAttribute('viewBox',`${c.x} ${c.y} ${c.w} ${c.h}`);this.svg.setAttribute('preserveAspectRatio','none');this.svg.innerHTML=this.content()+ (this.drag?.kind==='sketch'?`<polyline points="${this.drag.points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#355ccc" stroke-width="3"/>`:'');const rows=this.rows(),list=this.host.querySelector('#draw-objects');if(document.activeElement!==list){list.innerHTML=rows.map(r=>`<option value="${esc(r.id)}" ${r.id===this.selected?'selected':''}>${esc(r.text||r.kind)}</option>`).join('');}this.host.querySelector('#drawing-status').textContent=`${rows.length} shared objects · ${Math.round(1000/c.w*100)}% zoom${rows.length?'':' · Add a sticky note or shape to start.'}`;for(const r of rows)if(r.kind==='image'&&!this.urls.has(r.asset)&&!this.loading.has(r.asset)){this.loading.add(r.asset);getAsset(this.room.id,r.asset).then(blob=>{if(blob&&raster(blob.type)&&!this.destroyed){this.urls.set(r.asset,URL.createObjectURL(blob));this.render();}}).finally(()=>this.loading.delete(r.asset));}}
 inspect(){const o=this.rows().find(r=>r.id===this.selected);if(!o){this.inspector.innerHTML='<p>Select an object to change its text, shape, or position.</p>';return;}const choices=this.rows().filter(r=>r.kind!=='connector');this.inspector.innerHTML=`<form id="draw-form"><label class="field">Text / label<textarea id="draw-text" maxlength="1000">${esc(o.text)}</textarea></label><div class="field-grid">${(o.kind==='connector'?[]:o.kind==='sketch'?['x','y']:['x','y','w','h']).map(k=>`<label class="field">${({x:'X',y:'Y',w:'Width',h:'Height'})[k]}<input id="draw-${k}" type="number" value="${number(o[k])}" min="${k==='w'||k==='h'?10:-10000}" max="10000"></label>`).join('')}</div><label class="field">Color<input id="draw-color" type="color" value="${color(o.color)}"></label>${o.kind==='connector'?['from','to'].map(k=>`<label class="field">${k}<select id="draw-${k}">${choices.map(r=>`<option value="${r.id}" ${r.id===o[k]?'selected':''}>${esc(r.text||r.kind)}</option>`).join('')}</select></label>`).join(''):''}${o.kind==='image'?`<label class="field">Image<select id="draw-asset">${[...this.doc.getMap('files')].filter(([,f])=>!f.deleted&&raster(f.type)).map(([id,f])=>`<option value="${id}" ${id===o.asset?'selected':''}>${esc(f.name)}</option>`).join('')}</select></label>`:''}<button class="primary">Apply changes</button> <button type="button" id="draw-delete" class="text-button danger">Remove</button></form><p class="muted">Undo restores removed objects. Backups and snapshots include the drawing.</p>`;const q=s=>this.inspector.querySelector(s);q('#draw-form').onsubmit=e=>{e.preventDefault();const f={text:q('#draw-text').value,color:q('#draw-color').value};for(const k of ['x','y','w','h'])if(q('#draw-'+k))f[k]=number(q('#draw-'+k).value);for(const k of ['from','to','asset'])if(q('#draw-'+k))f[k]=q('#draw-'+k).value;this.change(o.id,Object.fromEntries(Object.entries(f).filter(([k,v])=>v!==o[k])));this.toast('Whiteboard object updated.');};q('#draw-delete').onclick=()=>{this.change(o.id,{deleted:true});this.selected=null;this.inspect();};}
 async document(requireAll=true){const urls=new Map(),rows=this.rows();for(const o of rows)if(o.kind==='image'){const blob=await getAsset(this.room.id,o.asset);if(!blob||!raster(blob.type)){if(requireAll)throw Error('Get every whiteboard image in Files before exporting.');continue;}urls.set(o.asset,`data:${blob.type};base64,${b64(new Uint8Array(await blob.arrayBuffer()))}`);}const b=this.bounds(),width=Math.min(3000,Math.max(600,Math.round(b.w))),height=Math.min(3000,Math.max(390,Math.round(width*b.h/b.w)));const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${b.x} ${b.y} ${b.w} ${b.h}" width="${width}" height="${height}"><rect x="${b.x}" y="${b.y}" width="${b.w}" height="${b.h}" fill="white"/>${this.content(urls,false)}</svg>`;return {svg,width,height};}
 async export(format){const {svg,width,height}=await this.document();if(format==='svg'){this.download('peerbench-whiteboard.svg',svg,'image/svg+xml');return;}const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d').drawImage(img,0,0,width,height);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));if(!blob)throw Error('PNG export unavailable. Try SVG.');this.download('peerbench-whiteboard.png',blob);}finally{URL.revokeObjectURL(url);}}
 destroy(){this.destroyed=true;this.map.unobserveDeep(this.observer);this.undo.destroy();for(const url of this.urls.values())URL.revokeObjectURL(url);}
}
